### ISSUE TITLE
How We Work styling

### ISSUE THREAD

**Issue by arthurHarding** [Fireflower2012/CooperationHullMainSite#102]
A couple of little things to sort out:

- Needs more padding at the top and bottom
- The pattern background can be swapped out for trees-pattern-grey, and the other img files can be deleted
- The image and the text are quite close to each other in the centre. Could they be moved apart a bit? I'm not sure exactly how they should look, but I'd use figma and the other sections as a guide and play around with it

Otherwise looks great

**Comment by lewis-conroy** [comment]
Fixed in another issue
