### ISSUE TITLE
Get .woff2 files for fonts

### ISSUE THREAD

**Issue by neefrehman** [Fireflower2012/CooperationHullMainSite#16]
I just noticed [this comment](https://github.com/Fireflower2012/CooperationHullMainSite/blob/53359e1cfa441825432f99725c06962910e803f3/CooperationHullMainSite/wwwroot/css/site.css#L38) in the CSS:

>TODO work out what file formats we need to get the font working right across multiple browsers and on mobile. Google open sans currently being used as a fallback

From experience, the `.woff2` (or `.woff`) file format is best for compatibility and file size.

**Comment by arthurHarding** [comment]
hey neef, I assigned this to you a couple weeks ago, are you happy to do it?

**Comment by neefrehman** [comment]
@arthurHarding sorry I missed this! Do we have a license for the font? If so, we'd usually get the files from the publisher/foundry.

**Comment by arthurHarding** [comment]
let me ask Abi, I think she introduced it first

**Comment by arthurHarding** [comment]
No we don’t have a license, I’m not sure how we ended up using it. Could you have a look for the files online for free? If we can’t find them we might have to choose a similar font

**Comment by neefrehman** [comment]
I had a quick look and could only find one weight of it available for free, funnily enough via Google fonts! I'm sure its possible to find the files online somewhere, though I wouldn't suggest using them without a license for legal reasons. It looks like the official publisher is My Fonts: https://www.myfonts.com/collections/basic-sans-font-latinotype
