### ISSUE TITLE
Sort out fonts properly and get rid of temp bodge

### ISSUE THREAD

**Issue by Fireflower2012** [Fireflower2012/CooperationHullMainSite#21]

**Comment by Fireflower2012** [comment]
Currently using Google Open Sans as a fallback font which needs to go when we have the proper font files etc sorted out

**Comment by arthurHarding** [comment]
@neefrehman if you're going to get the font files, please could you sort this out too?

**Comment by neefrehman** [comment]
Going to close this issue as its a bit duplicative of #16
