### ISSUE TITLE
set up proper css variables for site main colours

### ISSUE THREAD

**Issue by Fireflower2012** [Fireflower2012/CooperationHullMainSite#22]

**Comment by lewis-conroy** [comment]
i'm picking this one up 👍

**Comment by lewis-conroy** [comment]
this seems to have been done already:

https://github.dev/Fireflower2012/CooperationHullMainSite/blob/5b823ccd79c32359bd4a0483c5cd364cc01e8805/CooperationHullMainSite/wwwroot/css/site.css#L29

unless I've misunderstood the task? Let me know, I can pick up another item

**Comment by lewis-conroy** [comment]
Abi finished this
