### ISSUE TITLE
Main Nav Bar Navigation + Styling

### ISSUE THREAD

**Issue by Fireflower2012** [Fireflower2012/CooperationHullMainSite#37]

**Comment by arthurHarding** [comment]
On what-goes-where:

**NAV BAR**
_Visible at full width_
The Big Idea
How We Work
FAQs 
Donate

_Always in the burger menu_
Membership
The Pledge
Help to attend
Contact us

**Comment by lewis-conroy** [comment]
Just working on this the now

**Comment by lewis-conroy** [comment]
@arthurHarding does this mean that the hamburger should be visible at large width?

**Comment by Fireflower2012** [comment]
@lewis-conroy The Contact us page has been dropped for now and replaced by a mailto: link in the footer.
Also the routing for the How We work page is messed up in the current main branch.  Pr to fix that should be incoming shortly.

@arthurHarding Do we want the same thing in the nav bar or just leave it out for now.

**Comment by arthurHarding** [comment]
> [@arthurHarding](https://github.com/arthurHarding) does this mean that the hamburger should be visible at large width?

yes

and I think we could put the mailto: in the hamburger menu too
